In [69]:
import numpy as np
def foo_1(arr, target):
    if target in arr:
        x=np.abs(arr - target) # Calculating absolute differences
        index = np.argsort(x) # indices that would sort the array
        return index # result array with original elements and sorted indices
    else:
        return 'no item found'

In [70]:
arr = np.array([3, 8, 7, 7, 7, 7, 7, 8, 7, 10])

print(foo_1(arr, 7))

print(foo_1(arr, 11))

[2 3 4 5 6 8 1 7 9 0]
no item found


Import NumPy: import numpy as np imports the NumPy library and gives it the alias np for convenience.

Function Definition: The foo_1 function takes two parameters - arr (NumPy array) and target (the target value to find in the array).

Check if Target in Array: The if target in arr statement checks whether the target value is present in the array. If it is, the function proceeds; otherwise, it returns the string 'no item found'.

Calculate Absolute Differences: x = np.abs(arr - target) calculates the absolute differences between each element in the array arr and the target value.

Sort Indices: index = np.argsort(x) returns the indices that would sort the array x in ascending order.

Create Result Array: result = np.array(list(zip(arr[index], index))) creates a result array by zipping the original array elements at the sorted indices. The result is a 2D array where the first column contains the original array elements, and the second column contains the corresponding sorted indices.

Return Result: The function returns the result array if the target is found in the array; otherwise, it returns the string 'no item found'.

In [71]:
def count_nonzero_custom(arr, axis):
    if axis is None:
        return np.sum(arr == 0) # If axis is None, count non-zero elements in the entire array
    else:
        # If axis is specified, use apply_along_axis to count non-zero elements along that axis
        return np.apply_along_axis(lambda x: np.sum(x != 0), axis, arr) 

def foo_2(arr, axis=None):
    non_zero_count = count_nonzero_custom(arr, axis) # Call the helper function to get the count of non-zero elements
    if isinstance(non_zero_count, int): # If the result is an integer (axis=None), convert it to a list
        non_zero_count = [non_zero_count]
    return non_zero_count # Return the result, which is a list or an array containing the count of non-zero elements

count_nonzero_custom Function:

This function takes a NumPy array arr and an axis as parameters.
If axis is None, it calculates the total count of zero elements in the entire array using np.sum(arr == 0).
If axis is specified, it uses np.apply_along_axis to apply a lambda function that counts non-zero elements along the specified axis. 
The lambda function calculates the sum of elements that are not equal to zero along the specified axis.

foo_2 Function:

It calls the count_nonzero_custom function to calculate the count of non-zero elements based on the specified axis.
If the result is an integer (when axis is None), it converts it to a list.
It returns the result, which is a list or an array containing the count of non-zero elements along the specified axis.

In [72]:
arr = np.array([[1, 2, 3, 4],
                [0, 5, 0, 0],
                [2, 0, 1, 0]])

foo_2(arr, axis = 0)

array([2, 2, 2, 1])

In [73]:
arr1 = np.array([[[1, 2, 3, 4], [0, 5, 0, 0], [2, 0, 1, 0]],
                 [[2, 0, 1, 0], [0, 5, 0, 0], [1, 2, 3, 4]]])
foo_2(arr1 , axis = 2)

array([[4, 1, 2],
       [2, 1, 4]])

In [74]:
def foo_marks(scores):
    x = np.any(scores > 90, axis=1)
    result = scores[x]
    return result

In [75]:
student_score = np.array([[85, 89, 88],
                 [78, 89, 94],
                 [91, 87, 90],
                 [87, 95, 84]])

In [76]:
foo_marks(student_score)

array([[78, 89, 94],
       [91, 87, 90],
       [87, 95, 84]])

np.any(scores > 90, axis=1):

This line creates a boolean array x by using NumPy's any function along axis=1. It checks for each row (student) whether there is any score greater than 90 in any subject. The resulting boolean array has True where the condition is met (at least one subject score is greater than 90) and False otherwise.

result = scores[x]:

This line creates a subset of the original array scores by using the boolean array x as a mask. It selects only those rows (students) where the corresponding element in x is True. In other words, it includes only the rows where at least one subject score is above 90.
Return Result:

The function returns the resulting array, which includes only those rows (students) where at least one subject score is above 90.

In [77]:
def foo(sales_data):
    sd = {}
    for x, y in enumerate(sales_data):
        mean_sales = np.mean(y)
        median_sales = np.median(y)
        std_dev_sales = np.std(y)
        highest_sales_month = np.argmax(y) + 1
        sd[x + 1] = {
            'mean': mean_sales,
            'median': median_sales,
            'std_dev': std_dev_sales,
            'highest_sales_month': highest_sales_month
        }
    return sd

Initialize an Empty Dictionary sd:

sd = {} initializes an empty dictionary sd to store the calculated statistics for each product.

Iterate Over Each Row (Product) in sales_data:

for x, y in enumerate(sales_data): uses the enumerate function to iterate over each row (y) in sales_data. The variable x represents the index of the current row (product).

Calculate Statistics for Each Product:

Inside the loop, the following statistics are calculated for each product (row):
mean_sales: The mean of sales for the current product (np.mean(y)).
median_sales: The median of sales for the current product (np.median(y)).
std_dev_sales: The standard deviation of sales for the current product (np.std(y)).
highest_sales_month: The month with the highest sales for the current product (np.argmax(y) + 1 to convert to 1-based indexing).

Store Results in the Dictionary sd:

The calculated statistics for each product are stored in the dictionary sd. The key is the product index (x + 1 to convert to 1-based indexing), and the value is another dictionary containing the calculated statistics.
Return the Resulting Dictionary sd:

The function returns the final dictionary sd containing statistics for each product.

In [78]:
sales_data=np.array([[120, 150, 130, 110],
                    [200, 180, 220, 250],
                    [90, 100, 95, 110],
                    [300,280,320, 340]])

In [79]:
foo(sales_data)

{1: {'mean': 127.5,
  'median': 125.0,
  'std_dev': 14.79019945774904,
  'highest_sales_month': 2},
 2: {'mean': 212.5,
  'median': 210.0,
  'std_dev': 25.8602010819715,
  'highest_sales_month': 4},
 3: {'mean': 98.75,
  'median': 97.5,
  'std_dev': 7.39509972887452,
  'highest_sales_month': 4},
 4: {'mean': 310.0,
  'median': 310.0,
  'std_dev': 22.360679774997898,
  'highest_sales_month': 4}}

In [80]:
def freq(x):
    unique_values, counts = np.unique(x, return_counts=True)
    sorted = np.argsort(-counts)
    top_10_values = unique_values[sorted[:10]] # top 10 unique values are extracted based on the sorted indices
    top_10_counts = counts[sorted[:10]] # corresponding counts for the top 10 values are also extracted based on the sorted indices
    print("Top 10 most frequently occurring values:")
    for value, count in zip(top_10_values, top_10_counts):
        print(f"Value: {value}, Occurrences: {count}")

unique_values, counts = np.unique(x, return_counts=True):

This line uses NumPy's unique function to find the unique values in the array x along with their counts.

sorted_indices = np.argsort(-counts):

The indices are sorted in descending order based on the counts using argsort. The negative sign (-) is used to sort in descending order.

In [81]:
x=np.random.randint(1,100,1000)

In [82]:
freq(x)

Top 10 most frequently occurring values:
Value: 4, Occurrences: 19
Value: 45, Occurrences: 18
Value: 80, Occurrences: 17
Value: 93, Occurrences: 16
Value: 59, Occurrences: 16
Value: 20, Occurrences: 15
Value: 52, Occurrences: 15
Value: 9, Occurrences: 15
Value: 21, Occurrences: 15
Value: 46, Occurrences: 14
